version: '3.8'

services:
  app:
    container_name: image-classifier
    build: .
    command: uvicorn src.api.server:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
