version: '3.8'

services:
  app:
    container_name: image-classifier
    build: .
    command: uvicorn src.api.server:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    restart: unless-stopped  # Автоперезапуск, якщо контейнер падає

  bot:
    container_name: telegram-bot
    build: ./src/bot  # Використовує Dockerfile з папки бота
    volumes:
      - .:/app
    working_dir: /app/src/bot
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    depends_on:
      - app  # Бот запускається після бекенду
    restart: unless-stopped
